services:
  - type: web
    name: ad-verification-tool
    env: python
    buildCommand:buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
