services:
  - type: web
    name: ad-verification-tool
    # Specify Docker environment
    env: docker 
    # buildCommand and startCommand are now defined in the Dockerfile
    # PYTHON_VERSION is also defined in the Dockerfile
    envVars:
      # Keep environment variables needed at runtime
      - key: OPENAI_API_KEY
        sync: false
    # Keep health check and auto-deploy settings
    healthCheckPath: /
    autoDeploy: true
    # Render automatically detects Dockerfile in the root directory
    # If your Dockerfile is elsewhere, uncomment and set the path:
    # dockerfilePath: ./path/to/your/Dockerfile

