services:
  - type: web
    name: ad-verification-tool
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}  # Use Render's environment variables
    healthCheckPath: /
    autoDeploy: true
