services:
  - type: web
    name: ad-verification-tool
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
      python -m playwright install-deps chromium
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
